name: discover_morocco
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  lottie: ^2.4.0
  flutter_dotenv: ^5.1.0
  formz: ^0.4.1
  badges: ^3.1.1
  shimmer: ^3.0.0
  timelines: ^0.1.0
  like_button: ^2.0.5
  #cached_network_image: ^3.2.2
  scroll_snap_list:
    path: dependencies/scroll_snap_list

  uuid: ^3.0.7
  dio: ^5.3.1
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.6
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  shared_preferences: ^2.0.15
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  firebase_core: ^2.3.0
  firebase_auth: ^4.2.1
  firebase_messaging:
  cloud_firestore: ^4.1.0
  google_sign_in: ^6.1.4
  flutter_local_notifications:



  dart_vlc: ^0.4.0
  video_player: ^2.4.8
  image_picker: ^1.0.2



dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.16.0
  #dependency_validator:
  #device_preview: ^1.1.0
  #flutter_launcher_icons: ^0.13.1
  #flutter_native_splash: ^2.3.1

#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/logo_black.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21


#flutter_native_splash:
#  color: "#ffffff"
#  image: assets/images/logo_black.png
#  android: true
#  ios: true

flutter:
  #generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mock/
    - .env
  fonts:
    - family: manrope
      fonts:
        - asset: assets/fonts/manrope/manrope_extra_light.ttf
          weight: 200
        - asset: assets/fonts/manrope/manrope_light.ttf
          weight: 300
        - asset: assets/fonts/manrope/manrope_regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/manrope_medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/manrope_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/manrope/manrope_bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/manrope_extra_bold.ttf
          weight: 800


